### ISSUE TITLE
[Suggestion] Add ExtraPermission for ItemShops 

### ISSUE THREAD

**Issue by EverNife** [Blackixx/BSP-ItemShops#3]
Besides ``Worth`` and ``Item`` add ``ExtraPermission`` tag

Like this:

```
ShopName: PublicShop-Applied1
DisplayName: '➲  &0&lPublic Shop'
itemshop:
  MotorMolecular:
    Worth: 3200
    Item:
    - type:APPLIEDENERGISTICS2_TILEBLOCKMOLECULARASSEMBLER
    ExtraPermission: 'be.vip'
```
